# Support AncientLanguages development
# See docs/SUPPORT.md for detailed information

github: antonsoo
patreon: PLACEHOLDER_PATREON
open_collective: ancientlanguages
ko_fi: PLACEHOLDER_KOFI
liberapay: PLACEHOLDER_LIBERAPAY
custom:
  - PLACEHOLDER_STRIPE_PAYMENT_LINK
