# Support AncientLanguages development
# See docs/SUPPORT.md for detailed information

github: antonsoo
# patreon: # Uncomment and add username after account creation
# open_collective: # Uncomment and add username after account creation
# ko_fi: # Uncomment and add username after account creation
# liberapay: # Uncomment and add username after account creation
# custom: # Uncomment and add payment links after setup
#   - https://donate.stripe.com/your-link-here
