# Support PRAVIEL development
# See docs/SUPPORT.md for detailed information

github: antonsoo
patreon: AntonSoloviev
open_collective: antonsoloviev
ko_fi: antonsoloviev
liberapay: antonsoloviev
custom:
  - https://buy.stripe.com/6oU8wOfCe7ccbhefx0ew800
  - https://paypal.me/AntonS0
  - https://paypal.me/ancientlanguagesapp
