repos:
  # Hygiene & safety
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  # Python lint + format (fast)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: "^data/vendor/|^data/derived/"
      - id: ruff-format

  # Local policies
  - repo: local
    hooks:
      - id: validate-no-model-downgrades
        name: Block AI agents from downgrading models
        entry: C:/ProgramData/anaconda3/python.exe scripts/validate_no_model_downgrades.py
        language: system
        pass_filenames: false
        always_run: true

      - id: block-data-dirs
        name: Block committing vendor/derived data
        entry: bash scripts/hooks/run_python_hook.sh scripts/hooks/block_data_dirs.py
        language: system
        pass_filenames: false

      - id: forbid-api-keys
        name: Forbid obvious API keys in staged diff
        entry: bash scripts/hooks/run_python_hook.sh scripts/hooks/forbid_api_keys.py
        language: system
        pass_filenames: false
default_install_hook_types: [pre-commit, pre-push]
