# Railway deployment configuration for PRAVIEL FastAPI backend
# Documentation: https://docs.railway.com/reference/config-as-code

[build]
# Use the Dockerfile for consistent builds
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Only rebuild when backend code changes
watchPatterns = [
  "backend/**",
  "Dockerfile",
  "pyproject.toml",
  "alembic.ini",
  "alembic.docker.ini"
]

# Note: If builds still timeout, you may need to increase the timeout in Railway dashboard
# Railway's default build timeout is configurable per-project in the settings

[deploy]
# Railway will automatically detect PORT from environment
# Run database migrations before starting the server to ensure schema is up to date
# Use multiple workers for better performance (2 workers recommended for Railway Starter plan)
# --timeout-keep-alive 65: Slightly longer than typical load balancer timeout (60s)
# Set UVICORN_WORKERS=1 in Railway dashboard to disable workers if needed
startCommand = "python -m alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers ${UVICORN_WORKERS:-2} --timeout-keep-alive 65 --log-level info"

# Restart policy for resilience
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 300
