name: praviel
description: "PRAVIEL - AI-powered platform for learning 46 ancient languages with gamification, SRS, social features, and AI tutoring."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0  # Latest stable HTTP client
  flutter_riverpod: ^3.0.3  # State management
  riverpod: ^3.0.3
  go_router: ^16.3.0  # Declarative routing with deep linking ###### NEW (Oct-29-2025): Changed from `16.3.0` to `^16.3.0` to let pub pull newer 16.x/16.y without jumping to 17.x breaking changes
  shared_preferences: ^2.5.3  # For non-sensitive app preferences
  flutter_secure_storage: 10.0.0-beta.4  # Secure encrypted storage - BETA channel (DO NOT DOWNGRADE)
  audioplayers: ^6.5.1  # TTS audio playback
  google_fonts: ^6.3.2  # Professional typography
  dynamic_fonts: ^2.2.2  # Load fonts from custom CDN/R2 (for large CJK fonts)
  url_launcher: ^6.3.2  # Open donation links in browser
  qr_flutter: ^4.1.0  # QR codes for crypto addresses
  fl_chart: ^1.1.1  # Charts for analytics dashboard (upgraded)
  intl: ^0.20.2  # Date formatting for heatmaps (upgraded)
  confetti: ^0.8.0  # Confetti celebration animations (upgraded)
  lottie: ^3.3.2  # Complex animations
  rive: ^0.13.20  # Advanced interactive animations (2025 standard)
  flutter_animate: ^4.5.2  # Easy animation effects
  vibration: ^3.1.4  # Haptic feedback (upgraded)
  sensors_plus: ^7.0.0  # Gyroscope/accelerometer for parallax effects
  connectivity_plus: ^7.0.0  # Network connectivity monitoring for offline sync (upgraded)
  hive: ^2.2.3  # Local persistence for offline sync queues
  hive_flutter: ^1.1.0  # Flutter integrations for Hive storage
  path_provider: ^2.1.5  # Required by Hive for device storage access

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  #flutter_driver: ##### NEW (Oct-29-2025) flutter_driver removed (deprecated in favor of integration_test)
  #  sdk: flutter  ##### NEW (Oct-29-2025):
  flutter_lints: ^6.0.0
  web: ^1.1.1  # Upgraded


flutter:
  uses-material-design: true
  assets:
    - assets/config/dev.json
    - assets/config/prod.json
    - assets/languages_endonyms.json
    - assets/fonts/
    - assets/sounds/
    - assets/music/lat/
    - assets/music/grc-cls/
    - assets/music/grc-koi/
    - assets/music/hbo/
    # Note: CJK fonts (NotoSerifCJKsc, NotoSerifCJKjp) are loaded from R2, not bundled in fonts: section
  fonts:
    # Base UI fonts - Inter, Poppins, Montserrat loaded via google_fonts package
    # GentiumPlus for ancient text rendering
    - family: GentiumPlus
      fonts:
        - asset: assets/fonts/GentiumPlus-Regular.ttf
        - asset: assets/fonts/GentiumPlus-Italic.ttf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/Noto_Serif-NotoSerif-Regular.ttf

    # === CORE LANGUAGE FONTS (Languages 1-10) ===
    # 1. Classical Greek - Noto Sans (has Greek)
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans-NotoSans-Regular.ttf

    # 2. Classical Latin - Noto Sans (has Latin)
    # Covered by NotoSans above

    # 3. Old Egyptian - Hieroglyphs
    - family: NotoSansEgyptianHieroglyphs
      fonts:
        - asset: assets/fonts/Noto_Sans_Egyptian_Hieroglyphs-NotoSansEgyptianHieroglyphs-Regular.ttf

    # 4. Vedic Sanskrit - Brahmi
    - family: NotoSansBrahmi
      fonts:
        - asset: assets/fonts/Noto_Sans_Brahmi-NotoSansBrahmi-Regular.ttf

    # 5. Koine Greek - Noto Sans (has Greek)
    # Covered by NotoSans above

    # 6. Ancient Sumerian - Cuneiform
    - family: NotoSansCuneiform
      fonts:
        - asset: assets/fonts/Noto_Sans_Cuneiform-NotoSansCuneiform-Regular.ttf

    # 7. Yehudit (Paleo-Hebrew) - Phoenician script
    - family: NotoSansPhoenician
      fonts:
        - asset: assets/fonts/Noto_Sans_Phoenician-NotoSansPhoenician-Regular.ttf

    # 8. Old Church Slavonic - Glagolitic
    - family: NotoSansGlagolitic
      fonts:
        - asset: assets/fonts/Noto_Sans_Glagolitic-NotoSansGlagolitic-Regular.ttf

    # 9. Avestan
    - family: NotoSansAvestan
      fonts:
        - asset: assets/fonts/Noto_Sans_Avestan-NotoSansAvestan-Regular.ttf

    # 10. Pali - Brahmi
    # Covered by NotoSansBrahmi above

    # === ADDITIONAL LANGUAGE FONTS (Languages 11-36) ===
    # 11. Biblical Hebrew
    - family: NotoSansHebrew
      fonts:
        - asset: assets/fonts/Noto_Sans_Hebrew-NotoSansHebrew-Regular.ttf

    # 12. Ancient Aramaic - Imperial Aramaic
    - family: NotoSansImperialAramaic
      fonts:
        - asset: assets/fonts/Noto_Sans_Imperial_Aramaic-NotoSansImperialAramaic-Regular.ttf

    # 13. Classical Sanskrit - Devanagari
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/Noto_Sans_Devanagari-NotoSansDevanagari-Regular.ttf
    - family: NotoSerifDevanagari
      fonts:
        - asset: assets/fonts/Noto_Serif_Devanagari-NotoSerifDevanagari-Regular.ttf

    # 14. Akkadian - Cuneiform
    # Covered by NotoSansCuneiform above

    # 15. Old Norse - Runic
    - family: NotoSansRunic
      fonts:
        - asset: assets/fonts/Noto_Sans_Runic-NotoSansRunic-Regular.ttf

    # 16. Middle Egyptian - Hieroglyphs
    # Covered by NotoSansEgyptianHieroglyphs above

    # 17. Old English - Anglo-Saxon Runes
    # Covered by NotoSansRunic above

    # 18. Classical Chinese - CJK
    # NOTE: NotoSerifCJKsc is now loaded dynamically from R2 (see R2FontService)
    # This reduces bundle size by ~58MB

    # 19. Coptic (Sahidic)
    - family: NotoSansCoptic
      fonts:
        - asset: assets/fonts/Noto_Sans_Coptic-NotoSansCoptic-Regular.ttf

    # 20. Hittite - Cuneiform
    # Covered by NotoSansCuneiform above

    # 21. Classical Nahuatl - Latin with macrons
    # Covered by NotoSans above

    # 22. Classical Tibetan
    - family: NotoSerifTibetan
      fonts:
        - asset: assets/fonts/Noto_Serif_Tibetan-NotoSerifTibetan-Regular.ttf

    # 23. Old Japanese - CJK
    # NOTE: NotoSerifCJKjp is now loaded dynamically from R2 (see R2FontService)
    # This reduces bundle size by ~58MB

    # 24. Classical Quechua - Latin
    # Covered by NotoSans above

    # 25. Classical Arabic
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/Noto_Naskh_Arabic-NotoNaskhArabic-Regular.ttf

    # 26. Classical Syriac
    - family: NotoSansSyriac
      fonts:
        - asset: assets/fonts/Noto_Sans_Syriac-NotoSansSyriac-Regular.ttf
    - family: NotoSansSyriacEastern
      fonts:
        - asset: assets/fonts/Noto_Sans_Syriac_Eastern-NotoSansSyriacEastern-Regular.ttf

    # 27. Middle Persian (Pahlavi)
    - family: NotoSansInscriptionalPahlavi
      fonts:
        - asset: assets/fonts/Noto_Sans_Inscriptional_Pahlavi-NotoSansInscriptionalPahlavi-Regular.ttf

    # 28. Old Irish - Ogham
    - family: NotoSansOgham
      fonts:
        - asset: assets/fonts/Noto_Sans_Ogham-NotoSansOgham-Regular.ttf

    # 29. Gothic
    - family: NotoSansGothic
      fonts:
        - asset: assets/fonts/Noto_Sans_Gothic-NotoSansGothic-Regular.ttf

    # 30. Ge Ωez - Ethiopic
    - family: NotoSansEthiopic
      fonts:
        - asset: assets/fonts/Noto_Sans_Ethiopic-NotoSansEthiopic-Regular.ttf
    - family: NotoSerifEthiopic
      fonts:
        - asset: assets/fonts/Noto_Serif_Ethiopic-NotoSerifEthiopic-Regular.ttf

    # 31. Classical Tamil
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/Noto_Sans_Tamil-NotoSansTamil-Regular.ttf
    - family: NotoSerifTamil
      fonts:
        - asset: assets/fonts/Noto_Serif_Tamil-NotoSerifTamil-Regular.ttf

    # 32. Classical Armenian
    - family: NotoSansArmenian
      fonts:
        - asset: assets/fonts/Noto_Sans_Armenian-NotoSansArmenian-Regular.ttf
    - family: NotoSerifArmenian
      fonts:
        - asset: assets/fonts/Noto_Serif_Armenian-NotoSerifArmenian-Regular.ttf

    # 33. Sogdian
    - family: NotoSansSogdian
      fonts:
        - asset: assets/fonts/Noto_Sans_Sogdian-NotoSansSogdian-Regular.ttf
    - family: NotoSansOldSogdian
      fonts:
        - asset: assets/fonts/Noto_Sans_Old_Sogdian-NotoSansOldSogdian-Regular.ttf

    # 34. Ugaritic
    - family: NotoSansUgaritic
      fonts:
        - asset: assets/fonts/Noto_Sans_Ugaritic-NotoSansUgaritic-Regular.ttf

    # 35-36. Tocharian A/B - Brahmi
    # Covered by NotoSansBrahmi above

    # === PARTIAL COURSE FONTS ===
    # 1. Etruscan - Old Italic
    - family: NotoSansOldItalic
      fonts:
        - asset: assets/fonts/Noto_Sans_Old_Italic-NotoSansOldItalic-Regular.ttf

    # 2-4. Proto-Norse, Runic Old Norse - Runic
    # Covered by NotoSansRunic above

    # 3. Elamite - Cuneiform
    # Covered by NotoSansCuneiform above

    # 5. Old Persian
    - family: NotoSansOldPersian
      fonts:
        - asset: assets/fonts/Noto_Sans_Old_Persian-NotoSansOldPersian-Regular.ttf

    # 6. Classic Maya
    - family: NotoSansMayanNumerals
      fonts:
        - asset: assets/fonts/Noto_Sans_Mayan_Numerals-NotoSansMayanNumerals-Regular.ttf

    # 7. Old Turkic
    - family: NotoSansOldTurkic
      fonts:
        - asset: assets/fonts/Noto_Sans_Old_Turkic-NotoSansOldTurkic-Regular.ttf

    # 8-10. Phoenician, Moabite, Punic
    # Covered by NotoSansPhoenician above

    # === SUPPLEMENTARY FONTS ===
    # Georgian (for future use)
    - family: NotoSansGeorgian
      fonts:
        - asset: assets/fonts/Noto_Sans_Georgian-NotoSansGeorgian-Regular.ttf
    - family: NotoSerifGeorgian
      fonts:
        - asset: assets/fonts/Noto_Serif_Georgian-NotoSerifGeorgian-Regular.ttf

    # Cypriot (Linear B descendant, for reference)
    - family: NotoSansCypriot
      fonts:
        - asset: assets/fonts/Noto_Sans_Cypriot-NotoSansCypriot-Regular.ttf

    # Additional Ge'ez fonts
    - family: AbyssinicaSIL
      fonts:
        - asset: assets/fonts/Abyssinica_SIL-AbyssinicaSIL-Regular.ttf
    - family: Menbere
      fonts:
        - asset: assets/fonts/Menbere-Menbere-Regular.ttf
