name: flutter_reader
description: "Reader MVP for Iliad token analysis."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0  # Latest stable HTTP client
  flutter_riverpod: ^3.0.0  # State management
  riverpod: ^3.0.0
  shared_preferences: ^2.3.4  # For non-sensitive app preferences
  flutter_secure_storage: ^9.2.2  # Secure encrypted storage for tokens
  audioplayers: ^6.1.0  # TTS audio playback
  google_fonts: ^6.2.1  # Professional typography
  url_launcher: ^6.3.0  # Open donation links in browser
  qr_flutter: ^4.1.0  # QR codes for crypto addresses
  fl_chart: ^0.69.0  # Charts for analytics dashboard
  intl: ^0.19.0  # Date formatting for heatmaps
  confetti: ^0.7.0  # Confetti celebration animations
  lottie: ^3.1.2  # Complex animations
  flutter_animate: ^4.5.2  # Easy animation effects
  vibration: ^2.0.0  # Haptic feedback
  connectivity_plus: ^6.0.5  # Network connectivity monitoring for offline sync

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  web: ^0.5.1
  test: ^1.25.0


flutter:
  uses-material-design: true
  assets:
    - assets/config/dev.json
    - assets/fonts/
    - assets/sounds/
  fonts:
    - family: GentiumPlus
      fonts:
        - asset: assets/fonts/GentiumPlus-Regular.ttf
        - asset: assets/fonts/GentiumPlus-Italic.ttf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
