name: ancient_languages_app
description: "Comprehensive AI-powered language learning platform for Ancient Greek with gamification, SRS, social features, and AI tutoring."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0  # Latest stable HTTP client
  flutter_riverpod: ^3.0.0  # State management
  riverpod: ^3.0.0
  shared_preferences: ^2.3.4  # For non-sensitive app preferences
  flutter_secure_storage: 10.0.0-beta.4  # Secure encrypted storage for tokens (beta - uses newer platform packages)
  audioplayers: ^6.1.0  # TTS audio playback
  google_fonts: ^6.2.1  # Professional typography
  url_launcher: ^6.3.0  # Open donation links in browser
  qr_flutter: ^4.1.0  # QR codes for crypto addresses
  fl_chart: ^1.1.0  # Charts for analytics dashboard (upgraded)
  intl: ^0.20.0  # Date formatting for heatmaps (upgraded)
  confetti: ^0.8.0  # Confetti celebration animations (upgraded)
  lottie: ^3.1.2  # Complex animations
  flutter_animate: ^4.5.2  # Easy animation effects
  vibration: ^3.1.4  # Haptic feedback (upgraded)
  connectivity_plus: ^7.0.0  # Network connectivity monitoring for offline sync (upgraded)

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  web: ^1.1.0  # Upgraded
  test: ^1.25.0


flutter:
  uses-material-design: true
  assets:
    - assets/config/dev.json
    - assets/languages_endonyms.json
    - assets/fonts/
    - assets/sounds/
  fonts:
    - family: GentiumPlus
      fonts:
        - asset: assets/fonts/GentiumPlus-Regular.ttf
        - asset: assets/fonts/GentiumPlus-Italic.ttf
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    # Ancient script fonts for historically accurate rendering (INSTALLED)
    - family: Noto Sans Devanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-VariableFont_wdth,wght.ttf
    - family: Noto Sans Hebrew
      fonts:
        - asset: assets/fonts/NotoSansHebrew-VariableFont_wdth,wght.ttf
    - family: Noto Sans Glagolitic
      fonts:
        - asset: assets/fonts/NotoSansGlagolitic-Regular.ttf
    - family: Noto Sans Cuneiform
      fonts:
        - asset: assets/fonts/NotoSansCuneiform-Regular.ttf
    - family: Noto Sans Old Persian
      fonts:
        - asset: assets/fonts/NotoSansOldPersian-Regular.ttf
    - family: Noto Sans Avestan
      fonts:
        - asset: assets/fonts/NotoSansAvestan-Regular.ttf
    - family: Noto Sans Imperial Aramaic
      fonts:
        - asset: assets/fonts/NotoSansImperialAramaic-Regular.ttf
    - family: Noto Sans Phoenician
      fonts:
        - asset: assets/fonts/NotoSansPhoenician-Regular.ttf
    - family: Noto Sans Runic
      fonts:
        - asset: assets/fonts/NotoSansRunic-Regular.ttf
    - family: Noto Sans Linear B
      fonts:
        - asset: assets/fonts/NotoSansLinearB-Regular.ttf
    # Not installed yet (will use system fonts as fallback):
    # - Noto Serif Greek (for Greek - system fonts work well)
    # - Noto Sans Brahmi (for Pali - can download if needed)
    # - Noto Sans Egyptian Hieroglyphs (for Egyptian - can download if needed)
