name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]" pre-commit

      - name: Pre-commit (all files)
        run: pre-commit run --all-files

      - name: Unit tests (no DB)
        run: pytest -q

  db-integration:
    runs-on: ubuntu-latest
    needs: lint-and-unit
    env:
      DATABASE_URL: postgresql+asyncpg://app:app@localhost:5433/app
      DATABASE_URL_SYNC: postgresql+psycopg://app:app@localhost:5433/app
      PYTHONPATH: backend
      RUN_DB_TESTS: "1"
      REDIS_URL: redis://localhost:6379/0
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Start database
        run: |
          docker compose up -d db
          for i in {1..20}; do
            if docker compose exec -T db pg_isready -U app > /dev/null 2>&1; then
              break
            fi
            sleep 3
          done

      - name: Apply migrations
        run: python -m alembic -c alembic.ini upgrade head

      - name: Run DB-gated tests
        run: pytest -q tests/test_api_search.py tests/test_search_trgm_demo.py
